[build]
command = "npm install && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# Enhanced security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Production CORS headers (restrictive)
[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, X-Client-Info, ApiKey"
Access-Control-Max-Age = "86400"
Vary = "Origin"

# Cache for static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Function redirects removed - invalid .netlify path

# API redirects for backwards compatibility
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

# SPA fallback - serve React app for all routes (MUST be last)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

# Environment-specific configurations
[context.production.environment]
NODE_ENV = "production"
ENVIRONMENT = "production"

# Development-specific configuration
[context.deploy-preview]
[context.deploy-preview.environment]
NODE_ENV = "development"
ENVIRONMENT = "staging"

[[context.deploy-preview.headers]]
for = "/api/*"
[context.deploy-preview.headers.values]
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, X-Client-Info, ApiKey"
Access-Control-Allow-Credentials = "true"
Access-Control-Max-Age = "86400"
Vary = "Origin"

[context.branch-deploy]
[context.branch-deploy.environment]
NODE_ENV = "development"
ENVIRONMENT = "development"

[[context.branch-deploy.headers]]
for = "/api/*"
[context.branch-deploy.headers.values]
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, X-Client-Info, ApiKey"
Access-Control-Allow-Credentials = "true"
Access-Control-Max-Age = "86400"
Vary = "Origin"