[build]
command = "npm install --include=dev && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# API caching headers for IGDB proxy endpoints
[[headers]]
for = "/api/igdb/*"
[headers.values]
Cache-Control = "public, max-age=300, s-maxage=600, stale-while-revalidate=3600"
Vary = "Accept-Encoding, Authorization"
X-Cache-Status = "MISS"

# Cache for game data endpoints (longer cache since game data is more stable)
[[headers]]
for = "/api/games/*"
[headers.values]
Cache-Control = "public, max-age=1800, s-maxage=3600, stale-while-revalidate=7200"
Vary = "Accept-Encoding"

# Cache for search endpoints (shorter cache since search results change frequently)
[[headers]]
for = "/api/search/*"
[headers.values]
Cache-Control = "public, max-age=300, s-maxage=600, stale-while-revalidate=1800"
Vary = "Accept-Encoding"

# Cache for popular/trending endpoints
[[headers]]
for = "/api/popular/*"
[headers.values]
Cache-Control = "public, max-age=900, s-maxage=1800, stale-while-revalidate=3600"
Vary = "Accept-Encoding"

# Cache for static game assets (covers, screenshots)
[[headers]]
for = "/api/images/*"
[headers.values]
Cache-Control = "public, max-age=86400, s-maxage=172800, immutable"
Vary = "Accept-Encoding"

# Existing asset caching (keep your current settings)
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/manifest.json"
[headers.values]
Cache-Control = "public, max-age=3600"

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
X-XSS-Protection = "1; mode=block"
