-- Migration: Upgrade all game cover images from t_thumb to t_cover_big
-- This migration updates ~96,700 game records to use higher quality cover images
-- 
-- Background: Games were imported with low-quality thumbnail images (t_thumb: 90x128px)
-- This upgrades them to cover_big (264x374px) for better visual quality
--
-- Author: Generated by Claude Code
-- Date: 2025-08-29

-- Create a backup table first (optional, for safety)
-- Uncomment the next line if you want to keep a backup
-- CREATE TABLE game_cover_backup AS SELECT id, cover_url, pic_url FROM game WHERE cover_url LIKE '%t_thumb%' OR pic_url LIKE '%t_thumb%';

-- Update cover_url field: Replace t_thumb with t_cover_big
UPDATE game 
SET cover_url = REPLACE(cover_url, 't_thumb', 't_cover_big')
WHERE cover_url LIKE '%t_thumb%';

-- Update pic_url field: Replace t_thumb with t_cover_big  
UPDATE game 
SET pic_url = REPLACE(pic_url, 't_thumb', 't_cover_big')
WHERE pic_url LIKE '%t_thumb%';

-- Update the updated_at timestamp for affected records
UPDATE game 
SET updated_at = NOW()
WHERE cover_url LIKE '%t_cover_big%' OR pic_url LIKE '%t_cover_big%';

-- Create indexes on cover_url and pic_url if they don't exist (for performance)
-- These will help with future queries that filter by image URLs
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_game_cover_url') THEN
    CREATE INDEX idx_game_cover_url ON game(cover_url) WHERE cover_url IS NOT NULL;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_game_pic_url') THEN
    CREATE INDEX idx_game_pic_url ON game(pic_url) WHERE pic_url IS NOT NULL;
  END IF;
END
$$;

-- Add a comment to track this migration
COMMENT ON COLUMN game.cover_url IS 'Game cover image URL - upgraded to t_cover_big quality on 2025-08-29';
COMMENT ON COLUMN game.pic_url IS 'Game picture URL - upgraded to t_cover_big quality on 2025-08-29';

-- Output summary statistics
DO $$
DECLARE
  cover_big_count INTEGER;
  pic_big_count INTEGER;
  total_games INTEGER;
BEGIN
  SELECT COUNT(*) INTO cover_big_count FROM game WHERE cover_url LIKE '%t_cover_big%';
  SELECT COUNT(*) INTO pic_big_count FROM game WHERE pic_url LIKE '%t_cover_big%';
  SELECT COUNT(*) INTO total_games FROM game;
  
  RAISE NOTICE 'Migration completed successfully!';
  RAISE NOTICE 'Games with high-quality cover_url: % / %', cover_big_count, total_games;
  RAISE NOTICE 'Games with high-quality pic_url: % / %', pic_big_count, total_games;
END
$$;