-- Migration: Upgrade game cover images from t_thumb to t_cover_big (MANUAL CHUNKS)
-- Run these commands one at a time if the batched version causes issues
-- Each command updates a limited number of records to avoid deadlocks
--
-- Author: Generated by Claude Code
-- Date: 2025-08-29

-- STEP 1: Check current status
SELECT 
  COUNT(*) as total_games,
  COUNT(CASE WHEN cover_url LIKE '%t_thumb%' THEN 1 END) as thumb_cover_urls,
  COUNT(CASE WHEN pic_url LIKE '%t_thumb%' THEN 1 END) as thumb_pic_urls
FROM game;

-- STEP 2: Update cover_url in chunks (run multiple times until no more rows affected)
-- Each execution updates 500 records
UPDATE game 
SET 
  cover_url = REPLACE(cover_url, 't_thumb', 't_cover_big'),
  updated_at = NOW()
WHERE id IN (
  SELECT id FROM game 
  WHERE cover_url LIKE '%t_thumb%'
  ORDER BY id
  LIMIT 500
);

-- Check progress after each update
SELECT COUNT(*) as remaining_thumb_covers FROM game WHERE cover_url LIKE '%t_thumb%';

-- STEP 3: Update pic_url in chunks (run multiple times until no more rows affected)
-- Each execution updates 500 records
UPDATE game 
SET 
  pic_url = REPLACE(pic_url, 't_thumb', 't_cover_big'),
  updated_at = NOW()
WHERE id IN (
  SELECT id FROM game 
  WHERE pic_url LIKE '%t_thumb%'
  ORDER BY id
  LIMIT 500
);

-- Check progress after each update
SELECT COUNT(*) as remaining_thumb_pics FROM game WHERE pic_url LIKE '%t_thumb%';

-- STEP 4: When all updates are complete, create indexes (optional)
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_game_cover_url ON game(cover_url) WHERE cover_url IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_game_pic_url ON game(pic_url) WHERE pic_url IS NOT NULL;

-- STEP 5: Add comments to track the migration
COMMENT ON COLUMN game.cover_url IS 'Game cover image URL - upgraded to t_cover_big quality';
COMMENT ON COLUMN game.pic_url IS 'Game picture URL - upgraded to t_cover_big quality';

-- STEP 6: Verify the migration is complete
SELECT 
  COUNT(*) as total_games,
  COUNT(CASE WHEN cover_url LIKE '%t_cover_big%' THEN 1 END) as big_cover_urls,
  COUNT(CASE WHEN pic_url LIKE '%t_cover_big%' THEN 1 END) as big_pic_urls,
  COUNT(CASE WHEN cover_url LIKE '%t_thumb%' THEN 1 END) as remaining_thumb_covers,
  COUNT(CASE WHEN pic_url LIKE '%t_thumb%' THEN 1 END) as remaining_thumb_pics
FROM game;