-- Rollback Migration: Revert game cover images from t_cover_big back to t_thumb
-- This migration reverts the image quality upgrade if needed
-- 
-- WARNING: Only run this if you need to rollback the image quality upgrade
-- This will reduce image quality back to thumbnail size
--
-- Author: Generated by Claude Code  
-- Date: 2025-08-29

-- Revert cover_url field: Replace t_cover_big back to t_thumb
UPDATE game 
SET cover_url = REPLACE(cover_url, 't_cover_big', 't_thumb')
WHERE cover_url LIKE '%t_cover_big%';

-- Revert pic_url field: Replace t_cover_big back to t_thumb
UPDATE game 
SET pic_url = REPLACE(pic_url, 't_cover_big', 't_thumb')
WHERE pic_url LIKE '%t_cover_big%';

-- Update the updated_at timestamp for affected records
UPDATE game 
SET updated_at = NOW()
WHERE cover_url LIKE '%t_thumb%' OR pic_url LIKE '%t_thumb%';

-- Remove the comments added during upgrade
COMMENT ON COLUMN game.cover_url IS 'Game cover image URL';
COMMENT ON COLUMN game.pic_url IS 'Game picture URL';

-- Output rollback statistics
DO $$
DECLARE
  thumb_cover_count INTEGER;
  thumb_pic_count INTEGER;
  total_games INTEGER;
BEGIN
  SELECT COUNT(*) INTO thumb_cover_count FROM game WHERE cover_url LIKE '%t_thumb%';
  SELECT COUNT(*) INTO thumb_pic_count FROM game WHERE pic_url LIKE '%t_thumb%';
  SELECT COUNT(*) INTO total_games FROM game;
  
  RAISE NOTICE 'Rollback completed successfully!';
  RAISE NOTICE 'Games reverted to thumbnail cover_url: % / %', thumb_cover_count, total_games;
  RAISE NOTICE 'Games reverted to thumbnail pic_url: % / %', thumb_pic_count, total_games;
END
$$;