name: Generate package-lock.json

on:
  workflow_dispatch:
  push:
    branches:
      - UserLoginSys-1
    paths:
      - 'package.json'

permissions:
  contents: write

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Generate package-lock.json
        run: |
          # Remove any existing lock file
          rm -f package-lock.json
          # Generate fresh lock file
          npm install --package-lock-only
          
      - name: Check if package-lock.json was created
        id: check_file
        run: |
          if [ -f "package-lock.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "✅ package-lock.json created successfully"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "❌ package-lock.json was not created"
            exit 1
          fi
          
      - name: Commit and push if changed
        if: steps.check_file.outputs.exists == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add package-lock.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: add package-lock.json [skip ci]"
            git push
          fi
